[package]
name = "rust-led-mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.7"
serde_json = "1.0.81"
rpi-led-matrix = "0.4.0"
rumqttc = "0.12.0"